create table catalog (id bigint generated by default as identity, created_at timestamp default CURRENT_TIMESTAMP not null, product_id varchar(120) not null, product_name varchar(255) not null, stock integer not null, unit_price integer not null, primary key (id));

insert into catalog(product_id, product_name, stock, unit_price) values ('product1', 'product_name1', 100, 1500);
insert into catalog(product_id, product_name, stock, unit_price) values ('product2', 'product_name2', 300, 900);
insert into catalog(product_id, product_name, stock, unit_price) values ('product3', 'product_name3', 400, 1200);
